spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate: 
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    password: Xx9Z55buew9_
    username: root
    url: jdbc:mysql://localhost:3306/alura-fornecedor
  
