spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    password: Xx9Z55buew9_
    username: root
    url: jdbc:mysql://localhost:3306/alura-fornecedor
  properties:
    hibernate: 
      dialect: org.hibernate.dialect.MySQLDialect
